const creditCards = [
  {
    //信用卡編號
    seq: 1,
    // 係用卡名稱
    cardName: "中信Yahoo聯名商務鈦金卡",
    // 信用卡描述
    des: "綁定 Apple Pay、Google Pay、Samsung Pay 11% (回饋為超贈點，每月回饋上限200，每月刷1818)",
    // 信用卡網站
    link: "https://reurl.cc/e3m7zK",
  },
  {
    seq: 2,
    cardName: "陽信VISA/Mastercard",
    des: "綁定台灣Pay 10% (每卡每月上限3750)",
    link: "https://reurl.cc/ErZLj0",
  },
  {
    seq: 3,
    cardName: "凱基魔Buy卡",
    des: "綁定 Apple Pay、Google Pay 舊戶6% 新戶8% (當月支付需滿3000及登錄，新戶3000~3333 8% 舊戶3000~5000 6%)",
    link: "https://reurl.cc/GxbLjy",
  },
  {
    seq: 4,
    cardName: "台新玫瑰giving卡",
    des: "假日刷卡綁定台灣Pay 3%~5% (1~5000 => 5%  5001~166666 => 3%)；平日刷卡綁定台灣Pay  1%~3% (1~5000 => 3%  超過5000 => 1%)",
    link: "https://reurl.cc/VD5QzZ",
  },
  {
    seq: 5,
    cardName: "中信中華電信悠遊聯名卡",
    des: "綁定Hami Pay感應消費 3%",
    link: "https://reurl.cc/q514Vq",
  },
  {
    seq: 6,
    cardName: "華南櫃買贏家生活卡",
    des: "綁定 Apple Pay、Google Pay 5%、台灣Pay 7% (每月上限2000,5%回饋上限100)",
    link: "https://reurl.cc/zZWnYa",
  },
  {
    seq: 7,
    cardName: "彰銀my樂卡",
    des: "綁定 台灣Pay 5.5%~8.5% (1~3000 => 5.5%，3001~5000 => 8.5%，5001~6000 => 6.5%) 通路刷卡再多0.5%~2.5%，活動每月一號登錄",
    link: "https://mylove.bankchb.com/",
  },
  {
    seq: 8,
    cardName: "新光寰宇現金回饋卡",
    des: "綁定 Apple Pay、Google Pay 台灣Pay 3%  (25000內3%)",
    link: "https://reurl.cc/QLbyz5",
  },
  {
    seq: 9,
    cardName: "遠東樂家+卡",
    des: "綁定台灣Pay 3.5%~5.5% (1~5000 => 5.5% , 5001~6666 => 3.5%)",
    link: "https://www.feib.com.tw/upload/creditcard/YACard/index.html",
  },
  {
    seq: 10,
    cardName: "永豐55688聯名卡",
    des: "享2%  搭車當日享7% (加碼5%每月上限600，可刷12000，回饋為T幣可折抵車資或台鐵高鐵電影院KTV費用)",
    link: "https://reurl.cc/VD1ryb",
  },
  {
    seq: 11,
    cardName: "中信中華電信悠遊聯名卡",
    des: "綁定Hami Pay感應消費享 3%",
    link: "https://reurl.cc/j1GLvM",
  },
  {
    seq: 12,
    cardName: "星展eco卡",
    des: "享1.5%~3% (1.5%無上限+1.5%每月回饋上限100，6666內3%，回饋滿100才能抵帳單) 消費3000有額外 1.5% 回饋",
    link: "https://reurl.cc/Dy3Glj",
  },
  {
    seq: 13,
    cardName: "永豐幣倍卡",
    des: "綁定Apple Pay、Google Pay、Samsung Pay、Garmin Pay、Fitbit Pay享 3% (原始回饋1%+行動支付2%，懂匯上限100/超匯上限300，帳單需新增消費2000)",
    link: "https://reurl.cc/anG2e9",
  },
  {
    seq: 14,
    cardName: "富邦 JU 卡",
    des: "享 2% (J Points卡 , 需綁定Line Pay)",
    link: "https://reurl.cc/zZNx56",
  },
  {
    seq: 15,
    cardName: "聯邦賴點卡",
    des: "享 1.5%+0.5% (回饋為Linepoint,加碼0.5%需辦理本行自動扣繳)",
    link: "https://reurl.cc/6Z0rqO",
  },
  {
    seq: 16,
    cardName: "花旗現金回饋PLUS鈦金卡",
    des: "享 2% (回饋需滿300才能折抵帳單)",
    link: "https://reurl.cc/g2MK3V",
  },
  {
    seq: 17,
    cardName: "LineBank快點卡",
    des: "享 2% (每月回饋上限500LP)",
    link: "https://reurl.cc/RrXxoz",
  },
  {
    seq: 18,
    cardName: "聯邦理財型無限卡",
    des: "享 8% (年費12000,每月可折抵新增消費1080)",
    link: "https://reurl.cc/e3O1bM",
  },
  {
    seq: 19,
    cardName: "聯邦理財型白金卡",
    des: "享 8% (年費5000,每月可折抵新增消費450)",
    link: "https://reurl.cc/9Gp2Aa",
  },
];

const data = [
  {
    id: 1,
    category_name: "雲端發票",
    type: 1,
    invoice: "WF78087593",
    date: "2022/01/09",
    description: "Today buy an apple",
    price: 1000,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 2,
    category_id: 3,
    category_name: "薪資",
    type: 2,
    invoice: null,
    date: "2022/04/30",
    description: "This is my salary!!",
    created_at: "2022-05-01 10:59:35",
    updated_at: "2022-05-02 15:59:35",
    user_id: 3,
    price: 5000,
    record: "收入",
    revexpdetail: [],
  },
  {
    id: 3,
    category_name: "雲端發票",
    type: 2,
    invoice: "XW53079261",
    date: "2022/04/10",
    description: "Spotify AB",
    price: 268,
    record: "支出",
    revexpdetail: [],
  },
  {
    id: 4,
    category_name: "雲端發票",
    type: 1,
    invoice: "XW78087593",
    date: "2022/04/03",
    description: "Apple Distribution International",
    price: 90,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 5,
    category_name: "雲端發票",
    type: 1,
    invoice: "XW80634118",
    date: "2022/04/12",
    description: "Apple Distribution International",
    price: 150,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 6,
    category_name: "雲端發票",
    type: 1,
    invoice: "YB81589425",
    date: "2022/04/13",
    description: "全聯實業股份有限公司左營自由二分公司",
    price: 126,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 7,
    category_name: "雲端發票",
    type: 1,
    invoice: "YW43911368",
    date: "2022/04/05",
    description: "家福股份有限公司鼎山分公司",
    price: 1,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 8,
    category_name: "雲端發票",
    type: 1,
    invoice: "YW43931456",
    date: "2022/04/12",
    description: "家福股份有限公司鼎山分公司",
    price: 1,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 9,
    category_name: "雲端發票",
    type: 1,
    invoice: "YH99572534",
    date: "2022/04/02",
    description: "統一超商股份有限公司高雄巿第五十九分公司",
    price: 8,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 10,
    category_name: "雲端發票",
    type: 1,
    invoice: "ZC46354938",
    date: "2022/04/06",
    description: "新加坡商蝦皮娛樂電商有限公司台灣分公司",
    price: 3,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 11,
    category_name: "雲端發票",
    type: 1,
    invoice: "XW08561513",
    date: "2022/04/06",
    description: "東森得易購股份有限公司",
    price: 46,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 12,
    category_name: "雲端發票",
    type: 1,
    invoice: "YP41528453",
    date: "2022/04/18",
    description: "九易宇軒股份有限公司",
    price: 1,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 13,
    category_name: "雲端發票",
    type: 1,
    invoice: "YX18333405",
    date: "2022/04/18",
    description: "旺來興企業股份有限公司明誠分公司",
    price: 1,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 14,
    category_name: "雲端發票",
    type: 1,
    invoice: "YG98909289",
    date: "2022/04/21",
    description: "統一超商股份有限公司高雄巿第１４７分公司",
    price: 2,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 15,
    category_name: "雲端發票",
    type: 1,
    invoice: "YY76533065",
    date: "2022/03/03",
    description: "創業家兄弟股份有限公司",
    price: 17,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 16,
    category_name: "雲端發票",
    type: 1,
    invoice: "XZ72298926",
    date: "2022/03/03",
    description: "台灣屈臣氏個人用品商店股份有限公司六合分公司",
    price: 35,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 17,
    category_name: "雲端發票",
    type: 1,
    invoice: "ZC34377539",
    date: "2022/03/06",
    description: "新加坡商蝦皮娛樂電商有限公司台灣分公司",
    price: 13,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 18,
    category_name: "雲端發票",
    type: 1,
    invoice: "YN68366138",
    date: "2022/03/08",
    description: "富邦媒體科技股份有限公司",
    price: 1,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 19,
    category_name: "雲端發票",
    type: 1,
    invoice: "YU37786313",
    date: "2022/03/11",
    description: "新加坡商宜睿智慧股份有限公司台灣分公司",
    price: 10,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 20,
    category_name: "雲端發票",
    type: 1,
    invoice: "YC84230479",
    date: "2022/03/13",
    description: "全國加油站股份有限公司全國高雄大順加油站",
    price: 66,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 21,
    category_name: "雲端發票",
    type: 1,
    invoice: "ZC39512642",
    date: "2022/03/19",
    description: "新加坡商蝦皮娛樂電商有限公司台灣分公司",
    price: 1,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 22,
    category_name: "雲端發票",
    type: 1,
    invoice: "YV17710129",
    date: "2022/03/20",
    description: "路易莎職人咖啡股份有限公司高醫自由分公司",
    price: 45,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 23,
    category_name: "雲端發票",
    type: 1,
    invoice: "XY43913470",
    date: "2022/03/30",
    description: "全家便利商店股份有限公司高雄市第二六八門市部",
    price: 6,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 24,
    category_name: "雲端發票",
    type: 1,
    invoice: "AB67639594",
    date: "2022/05/03",
    description: "Apple Distribution International",
    price: 90,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 25,
    category_name: "雲端發票",
    type: 1,
    invoice: "BC31543542",
    date: "2022/05/01",
    description: "惠康百貨股份有限公司南屏分公司",
    price: 1,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 26,
    category_name: "雲端發票",
    type: 1,
    invoice: "BJ48226414",
    date: "2022/05/06",
    description: "新加坡商蝦皮娛樂電商有限公司台灣分公司",
    price: 1,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 27,
    category_name: "雲端發票",
    type: 1,
    invoice: "BJ49042193",
    date: "2022/05/07",
    description: "新加坡商蝦皮娛樂電商有限公司台灣分公司",
    price: 2,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 28,
    category_name: "雲端發票",
    type: 1,
    invoice: "AT68538293",
    date: "2022/05/08",
    description: "富邦媒體科技股份有限公司",
    price: 8,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
  {
    id: 29,
    category_name: "雲端發票",
    type: 1,
    invoice: "BK21897724",
    date: "2022/05/08",
    description: "祈侑企業社出境營業處",
    price: 180,
    record: "支出",
    revexpdetail: ["Apple", "watermelon", "orange"],
  },
];

export { creditCards, data };
